"use client";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase-browser";

const CATEGORIES = ["الكل","إلكترونيات","أزياء","المنزل","ألعاب","سيارات","جمال","رياضة","أخرى"];
const money = n => `${Number(n || 0).toLocaleString("ar-EG")} ج.م`;

export default function Store(){
  const db = supabase();
  const [products,setProducts]=useState([]),[cart,setCart]=useState([]),[q,setQ]=useState(""),[category,setCategory]=useState("الكل"),[loading,setLoading]=useState(true),[supportOpen,setSupportOpen]=useState(false),[support,setSupport]=useState({name:"",phone:"",message:""}),[supportMsg,setSupportMsg]=useState("");

  useEffect(()=>{ let active=true; db.from("products").select("*").order("created_at",{ascending:false}).then(({data,error})=>{ if(active){setProducts(error?[]:(data||[]));setLoading(false)} }); return()=>{active=false}; },[]);
  const filtered=useMemo(()=>products.filter(p=>{const text=`${p.name||""} ${p.category||""} ${p.description||""}`.toLowerCase();return text.includes(q.toLowerCase())&&(category==="الكل"||p.category===category)}),[products,q,category]);
  const cartTotal=cart.reduce((s,p)=>s+Number(p.price||0),0);
  const add=p=>setCart(c=>[...c,p]);
  const remove=id=>setCart(c=>{const i=c.findIndex(x=>x.id===id);return i<0?c:[...c.slice(0,i),...c.slice(i+1)]});
  async function sendSupport(e){e.preventDefault();setSupportMsg("");if(!support.message.trim())return;const {error}=await db.from("support_messages").insert({name:support.name.trim()||null,phone:support.phone.trim()||null,message:support.message.trim()});if(error){setSupportMsg("تعذر إرسال الرسالة. تأكد من إعداد قاعدة البيانات.");return}setSupport({name:"",phone:"",message:""});setSupportMsg("تم إرسال رسالتك للدعم بنجاح. سنراجعها قريبًا.");}
  async function checkout(){if(!cart.length)return alert("السلة فارغة");const name=prompt("الاسم بالكامل");const phone=prompt("رقم الهاتف");const address=prompt("العنوان بالتفصيل");if(!name||!phone||!address)return;const payment=prompt("طريقة الدفع: cod أو visa أو mastercard","cod")||"cod";const {data:order,error}=await db.from("orders").insert({customer_name:name,phone,address,payment_method:payment,total:cartTotal,status:"pending"}).select().single();if(error)return alert(error.message);const items=cart.map(p=>({order_id:order.id,product_id:p.id,quantity:1,price:p.price}));const {error:itemError}=await db.from("order_items").insert(items);if(itemError)return alert(itemError.message);setCart([]);alert(`تم إنشاء الطلب بنجاح. رقم الطلب: ${order.id}`)}

  return <main className="shoply-app" dir="rtl">
    <header className="topbar"><button className="brand-button" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})}><span className="brand-mark">S</span><span><b>شوبلي</b><small>SHOPLY</small></span></button><form className="search" onSubmit={e=>e.preventDefault()}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="دور على حاجة..."/><button>⌕</button></form><nav><a href="#shop">تسوق</a><a href="#cart">طلباتي</a><a href="/login">دخول الإدارة</a></nav><button className="cart-button" onClick={()=>document.getElementById("cart")?.scrollIntoView({behavior:"smooth"})}>🛒<b>{cart.length}</b></button></header>
    <section className="hero"><div className="hero-copy"><span className="eyebrow">احتياجاتك اليومية في مكان واحد</span><h1>اختيارات حلوة،<br/><em>على باب بيتك.</em></h1><p>كل اللي بتحبه من المحل اللي تعرفه، بطريقة أسهل وأسرع. اختار، اطلب، وإحنا نوصل.</p><div className="hero-points"><span>✓ توصيل موثوق</span><span>✓ دفع عند الاستلام</span></div></div></section>
    <section className="section" id="shop"><div className="section-head"><div><span className="eyebrow">اختار براحتك</span><h2>موجود النهارده</h2></div></div><div className="filters"><div className="chips">{CATEGORIES.map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div></div>{loading?<div className="empty"><div className="spinner"/>جاري تحميل المنتجات...</div>:filtered.length===0?<div className="empty"><div className="empty-icon">🛍️</div><h3>مفيش منتجات مضافة حاليًا</h3><p>المنتجات بتظهر هنا بعد ما تضيفها من لوحة الإدارة.</p></div>:<div className="product-grid">{filtered.map(p=><article className="product-card" key={p.id}><div className="product-image">{p.image?<img src={p.image} alt={p.name}/>:<span>📦</span>}</div><div className="product-meta"><span>{p.category||"أخرى"}</span><i/> </div><h3>{p.name}</h3><p>{p.description||""}</p><div className="product-bottom"><strong>{money(p.price)}</strong><button onClick={()=>add(p)}>+</button></div></article>)}</div>}</section>
    <section className="trust"><div>🚚<b>توصيل لحد عندك</b><small>بنوصل طلبك بأمان</small></div><div>💳<b>دفع بالطريقة اللي تريحك</b><small>كاش أو كروت، القرار قرارك</small></div><button onClick={()=>{setSupportOpen(true);setSupportMsg("")}}>☎️<b>إحنا قريبين</b><small>دعم حقيقي لما تحتاج مساعدة</small></button></section>
    <section className="cart-section" id="cart"><div><span className="eyebrow">راجع طلبك</span><h2>السلة ({cart.length})</h2></div>{!cart.length?<p className="empty-cart">السلة فاضية حاليًا.</p>:<><div className="cart-list">{cart.map((p,i)=><div className="cart-row" key={`${p.id}-${i}`}><span>{p.name}</span><b>{money(p.price)}</b><button onClick={()=>remove(p.id)}>حذف</button></div>)}</div><div className="cart-total"><span>الإجمالي</span><strong>{money(cartTotal)}</strong></div><button className="primary full" onClick={checkout}>إتمام الطلب</button></>}</section>
    <footer>© {new Date().getFullYear()} شوبلي — متجر محلي بطعم البيت.</footer>
    {supportOpen&&<div className="modal-backdrop" onClick={()=>setSupportOpen(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSupportOpen(false)}>×</button><span className="eyebrow">دعم شوبلي</span><h2>إحنا معاك</h2><p>ابعت رسالتك للدعم من هنا، وهتتسجل مباشرة في لوحة الإدارة.</p><form onSubmit={sendSupport}><input placeholder="اسمك (اختياري)" value={support.name} onChange={e=>setSupport({...support,name:e.target.value})}/><input placeholder="رقم الهاتف (اختياري)" value={support.phone} onChange={e=>setSupport({...support,phone:e.target.value})}/><textarea required placeholder="اكتب محتاج مساعدة في إيه؟" value={support.message} onChange={e=>setSupport({...support,message:e.target.value})}/><button className="primary full">إرسال للدعم</button></form>{supportMsg&&<p className="support-message">{supportMsg}</p>}</div></div>}
  </main>
}
